***IMPORTING LIBRARIES***

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

USING DATASETS DOWNLOADED FROM <span style="color:blue">**FAO STATS**</span>

1. Pakistan's Fertilizers consumption in nutrients
2. Turkiye's Fertilizers consumption in nutrients

><span style="color:red">Checking head informations </span>

In [5]:
import pandas as pd
turkiye = pd.read_csv("turkiye.csv")
turkiye.head(5)

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1961,1961,t,54479,A,Official figure,Official data from questionnaire
1,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),1961,1961,t,18657,A,Official figure,Official data from questionnaire
2,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3104,Nutrient potash K2O (total),1961,1961,t,1649,A,Official figure,Official data from questionnaire
3,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1962,1962,t,38362,A,Official figure,Official data from questionnaire
4,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),1962,1962,t,34277,A,Official figure,Official data from questionnaire

In [6]:
import pandas as pd
pak = pd.read_csv("pak.csv")
pak.head(5)

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1961,1961,t,41659,A,Official figure,Official data from questionnaire
1,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),1961,1961,t,500,A,Official figure,Official data from questionnaire
2,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1962,1962,t,41160,A,Official figure,Official data from questionnaire
3,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),1962,1962,t,210,A,Official figure,Official data from questionnaire
4,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1963,1963,t,67620,A,Official figure,Official data from questionnaire

 ><span style="color:red">Shaping Dataframes</span>

In [11]:
pak.shape
turkiye.shape

(189, 15)

 ><span style="color:red">Listing Column Names </span>
(Shows all column names in each DataFrame.)

In [12]:
pak.columns
turkiye.columns

Index(['Domain Code', 'Domain', 'Area Code', 'Area', 'Element Code', 'Element',
       'Item Code', 'Item', 'Year Code', 'Year', 'Unit', 'Value', 'Flag',
       'Flag Description', 'Note'],
      dtype='object')

 ><span style="color:red">Basic Information About Data </span>

In [13]:
pak.info()
turkiye.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       184 non-null    object
 1   Domain            184 non-null    object
 2   Area Code         184 non-null    int64
 3   Area              184 non-null    object
 4   Element Code      184 non-null    int64
 5   Element           184 non-null    object
 6   Item Code         184 non-null    int64
 7   Item              184 non-null    object
 8   Year Code         184 non-null    int64
 9   Year              184 non-null    int64
 10  Unit              184 non-null    object
 11  Value             184 non-null    int64
 12  Flag              184 non-null    object
 13  Flag Description  184 non-null    object
 14  Note              179 non-null    object
dtypes: int64(6), object(9)
memory usage: 21.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189 entries, 0 to 188
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       189 non-null    object
 1   Domain            189 non-null    object
 2   Area Code         189 non-null    int64
 3   Area              189 non-null    object
 4   Element Code      189 non-null    int64
 5   Element           189 non-null    object
 6   Item Code         189 non-null    int64
 7   Item              189 non-null    object
 8   Year Code         189 non-null    int64
 9   Year              189 non-null    int64
 10  Unit              189 non-null    object
 11  Value             189 non-null    int64
 12  Flag              189 non-null    object
 13  Flag Description  189 non-null    object
 14  Note              189 non-null    object
dtypes: int64(6), object(9)
memory usage: 22.3+ KB

 ><span style="color:red">Descriptive Stats </span>

In [15]:
pak.describe()

,Area Code,Element Code,Item Code,Year Code,Year,Value
count,184.0,184.0,184.000000,184.000000,184.000000,1.840000e+02
mean,165.0,5157.0,3102.972826,1992.788043,1992.788043,7.635889e+05
std,0.0,0.0,0.812687,17.828376,17.828376,1.040835e+06
min,165.0,5157.0,3102.000000,1961.000000,1961.000000,1.440000e+02
25%,165.0,5157.0,3102.000000,1977.750000,1977.750000,2.886075e+04
50%,165.0,5157.0,3103.000000,1993.000000,1993.000000,3.178865e+05
75%,165.0,5157.0,3104.000000,2008.000000,2008.000000,9.937248e+05
max,165.0,5157.0,3104.000000,2023.000000,2023.000000,3.808775e+06

In [16]:
turkiye.describe()

,Area Code,Element Code,Item Code,Year Code,Year,Value
count,189.0,189.0,189.000000,189.00000,189.00000,1.890000e+02
mean,223.0,5157.0,3103.000000,1992.00000,1992.00000,5.198054e+05
std,0.0,0.0,0.818665,18.23254,18.23254,5.162106e+05
min,223.0,5157.0,3102.000000,1961.00000,1961.00000,5.740000e+02
25%,223.0,5157.0,3102.000000,1976.00000,1976.00000,7.229900e+04
50%,223.0,5157.0,3103.000000,1992.00000,1992.00000,4.702580e+05
75%,223.0,5157.0,3104.000000,2008.00000,2008.00000,7.636390e+05
max,223.0,5157.0,3104.000000,2023.00000,2023.00000,2.052685e+06

# Combining Datasets

In [24]:
pak['Country']= 'Pakistan'
turkiye['Country']= 'Turkiye'

In [32]:
turkiye.head(5)

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note,Country
0,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1961,1961,t,54479,A,Official figure,Official data from questionnaire,Turkiye
1,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),1961,1961,t,18657,A,Official figure,Official data from questionnaire,Turkiye
2,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3104,Nutrient potash K2O (total),1961,1961,t,1649,A,Official figure,Official data from questionnaire,Turkiye
3,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1962,1962,t,38362,A,Official figure,Official data from questionnaire,Turkiye
4,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),1962,1962,t,34277,A,Official figure,Official data from questionnaire,Turkiye

In [33]:
combined = pd.concat([pak, turkiye], ignore_index=True)

In [38]:
combined[['Country','Value']]
combined.head(3)
# combined.tail(3)

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note,Country
0,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1961,1961,t,41659,A,Official figure,Official data from questionnaire,Pakistan
1,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),1961,1961,t,500,A,Official figure,Official data from questionnaire,Pakistan
2,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1962,1962,t,41160,A,Official figure,Official data from questionnaire,Pakistan

In [41]:
combined[['Country','Year', 'Value']].sample(10)

      Country  Year    Value
41   Pakistan  1976   117900
29   Pakistan  1972    48730
202   Turkiye  1967   138140
268   Turkiye  1989  1140445
65   Pakistan  1984   293829
179  Pakistan  2022   743985
78   Pakistan  1988    24533
297   Turkiye  1998    88500
141  Pakistan  2009    15499
157  Pakistan  2015  3160507

In [42]:
pak_head= combined[combined['Country']=='Pakistan'].head(3)

In [43]:
tur_head= combined[combined['Country']=='Turkiye'].head(3)

In [44]:
small= pd.concat([pak_head, tur_head])
small

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note,Country
0,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1961,1961,t,41659,A,Official figure,Official data from questionnaire,Pakistan
1,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),1961,1961,t,500,A,Official figure,Official data from questionnaire,Pakistan
2,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1962,1962,t,41160,A,Official figure,Official data from questionnaire,Pakistan
184,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1961,1961,t,54479,A,Official figure,Official data from questionnaire,Turkiye
185,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),1961,1961,t,18657,A,Official figure,Official data from questionnaire,Turkiye
186,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3104,Nutrient potash K2O (total),1961,1961,t,1649,A,Official figure,Official data from questionnaire,Turkiye

In [46]:
small[['Country','Year', 'Value']]

      Country  Year  Value
0    Pakistan  1961  41659
1    Pakistan  1961    500
2    Pakistan  1962  41160
184   Turkiye  1961  54479
185   Turkiye  1961  18657
186   Turkiye  1961   1649

><span style="color:red">Filtering Rows</span>

1. For Seperate filtering

In [ ]:
pak[pak['Year'] >2019 ]

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note,Country
172,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3102,Nutrient nitrogen N (total),2020,2020,t,3533784,A,Official figure,Official data from questionnaire,Pakistan
173,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),2020,2020,t,1204060,A,Official figure,Official data from questionnaire,Pakistan
174,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3104,Nutrient potash K2O (total),2020,2020,t,60973,A,Official figure,Official data from questionnaire,Pakistan
175,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3102,Nutrient nitrogen N (total),2021,2021,t,3714997,A,Official figure,Official data from questionnaire,Pakistan
176,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),2021,2021,t,1110382,A,Official figure,Official data from questionnaire,Pakistan
177,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3104,Nutrient potash K2O (total),2021,2021,t,77867,A,Official figure,Official data from questionnaire,Pakistan
178,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3102,Nutrient nitrogen N (total),2022,2022,t,3666805,A,Official figure,Official data from questionnaire,Pakistan
179,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),2022,2022,t,743985,A,Official figure,Official data from questionnaire,Pakistan
180,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3104,Nutrient potash K2O (total),2022,2022,t,30508,A,Official figure,Official data from questionnaire,Pakistan
181,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3102,Nutrient nitrogen N (total),2023,2023,t,3808775,A,Official figure,Official data from questionnaire,Pakistan
182,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),2023,2023,t,994885,A,Official figure,Official data from questionnaire,Pakistan
183,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3104,Nutrient potash K2O (total),2023,2023,t,45735,A,Official figure,Official data from questionnaire,Pakistan

2. For combined Filtering to check trends and comparison

>Shows only data after 1800

In [59]:
filtering = small[small['Year']>1800]
filtering [['Country','Year','Value']]

      Country  Year  Value
0    Pakistan  1961  41659
1    Pakistan  1961    500
2    Pakistan  1962  41160
184   Turkiye  1961  54479
185   Turkiye  1961  18657
186   Turkiye  1961   1649

><span style ="color:red">Checking Missing Values</span>

In [ ]:
pak.isnull().sum()

Domain Code         0
Domain              0
Area Code           0
Area                0
Element Code        0
Element             0
Item Code           0
Item                0
Year Code           0
Year                0
Unit                0
Value               0
Flag                0
Flag Description    0
Note                0
Country             0
dtype: int64

In [61]:
turkiye.isnull().sum()

Domain Code         0
Domain              0
Area Code           0
Area                0
Element Code        0
Element             0
Item Code           0
Item                0
Year Code           0
Year                0
Unit                0
Value               0
Flag                0
Flag Description    0
Note                0
Country             0
dtype: int64

><span style ="color:red">Dropping Missing Values</span>

In [62]:
pak.dropna()
turkiye.dropna()

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note,Country
0,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1961,1961,t,54479,A,Official figure,Official data from questionnaire,Turkiye
1,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),1961,1961,t,18657,A,Official figure,Official data from questionnaire,Turkiye
2,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3104,Nutrient potash K2O (total),1961,1961,t,1649,A,Official figure,Official data from questionnaire,Turkiye
3,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1962,1962,t,38362,A,Official figure,Official data from questionnaire,Turkiye
4,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),1962,1962,t,34277,A,Official figure,Official data from questionnaire,Turkiye
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),2022,2022,t,603558,A,Official figure,Official data from questionnaire,Turkiye
185,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3104,Nutrient potash K2O (total),2022,2022,t,130747,A,Official figure,Official data from questionnaire,Turkiye
186,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3102,Nutrient nitrogen N (total),2023,2023,t,1948185,A,Official figure,Official data from questionnaire,Turkiye
187,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),2023,2023,t,735854,A,Official figure,Official data from questionnaire,Turkiye
188,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3104,Nutrient potash K2O (total),2023,2023,t,145768,A,Official figure,Official data from questionnaire,Turkiye

>(*No missing values was present*)

In [64]:
small[['Country','Value']]

      Country  Value
0    Pakistan  41659
1    Pakistan    500
2    Pakistan  41160
184   Turkiye  54479
185   Turkiye  18657
186   Turkiye   1649

><span style= "color:red">Adding a New Column</span>

In [68]:
small['Value_Double'] = small['Value'] * 2
small[['Country','Value_Double']]

      Country  Value_Double
0    Pakistan         83318
1    Pakistan          1000
2    Pakistan         82320
184   Turkiye        108958
185   Turkiye         37314
186   Turkiye          3298

><span style= "color:red">Dropping a Column</span>

In [71]:
small.drop('Value', axis=1)

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Flag,Flag Description,Note,Country,Value_Double
0,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1961,1961,t,A,Official figure,Official data from questionnaire,Pakistan,83318
1,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),1961,1961,t,A,Official figure,Official data from questionnaire,Pakistan,1000
2,RFN,Fertilizers by Nutrient,165,Pakistan,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1962,1962,t,A,Official figure,Official data from questionnaire,Pakistan,82320
184,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3102,Nutrient nitrogen N (total),1961,1961,t,A,Official figure,Official data from questionnaire,Turkiye,108958
185,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3103,Nutrient phosphate P2O5 (total),1961,1961,t,A,Official figure,Official data from questionnaire,Turkiye,37314
186,RFN,Fertilizers by Nutrient,223,Türkiye,5157,Agricultural Use,3104,Nutrient potash K2O (total),1961,1961,t,A,Official figure,Official data from questionnaire,Turkiye,3298

><span style="color:red">Using iloc (index-based selection)

In [76]:
pak.iloc[0:5, 0:3]

  Domain Code                   Domain  Area Code
0         RFN  Fertilizers by Nutrient        165
1         RFN  Fertilizers by Nutrient        165
2         RFN  Fertilizers by Nutrient        165
3         RFN  Fertilizers by Nutrient        165
4         RFN  Fertilizers by Nutrient        165

><span style="color:red">Grouping

In [83]:
combined.groupby('Country')['Value'].mean()

Country
Pakistan    763588.913043
Turkiye     519805.407407
Name: Value, dtype: float64